name: main

on: [push, pull_request]

jobs:
  publish-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Render contacts block
        uses: chuhlomin/render-template@v1.6
        with:
          template: templates/contacts_block.template.md
          result_path: rendered/contacts_block.md
          vars: |
            email: ${{ vars.CONTACTS_BLOCK_EMAIL }}
            tg_url: ${{ vars.CONTACTS_BLOCK_TG_URL }}
      - name: Set current date
        run: echo "HUMANIZED_DATETIME=$(date '+%B %dth, %Y, %H:%m UTC')" >> $GITHUB_ENV
      - name: Render disclaimer
        uses: chuhlomin/render-template@v1.6
        with:
          template: templates/generated_disclaimer.template.md
          result_path: rendered/generated_disclaimer.md
          vars: |
            datetime: ${{ env.HUMANIZED_DATETIME }}
      - name: Render CV.md
        run: ./scripts/insert_templates.py README.md CV.md
      - name: Render CV.pdf
        uses: khvn26/markdown-to-pdf@v1.3.0
        with:
          input_path: CV.md
          output_dir: pdfs
          theme: styles/custom.css
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs/*
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        name: Upload release CV.pdf
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pdfs/CV.pdf
          asset_name: CV.pdf
          asset_content_type: application/pdf
